package com.softwareverde.smartcity.parcel;

import com.softwareverde.json.Json;
import com.softwareverde.util.DateUtil;

import java.util.Date;

public class ParcelJsonAdapter {
    public Json toJson(final Parcel parcel) {
        final Long id = parcel.getId();
        final String parcelId = parcel.getParcelId();
        final Double exemptPropertyAppraisalLandValue = parcel.getExemptPropertyAppraisalLandValue();
        final Double exemptPropertyAppraisalBuildingValue = parcel.getExemptPropertyAppraisalBuildingValue();
        final Double exemptPropertyAppraisalTotalValue = parcel.getExemptPropertyAppraisalTotalValue();
        final Double taxablePropertyAppraisalLandValue = parcel.getTaxablePropertyAppraisalLandValue();
        final Double taxablePropertyAppraisalBuildingValue = parcel.getTaxablePropertyAppraisalBuildingValue();
        final Double taxablePropertyAppraisalTotalValue = parcel.getTaxablePropertyAppraisalTotalValue();
        final String auditorsMapNumber = parcel.getAuditorsMapNumber();
        final String auditorsRoutingSequence = parcel.getAuditorsRoutingSequence();
        final String appraisalLandUseCode = parcel.getAppraisalLandUseCode();
        final String currentAgriculturalUseValue = parcel.getCurrentAgriculturalUseValue();
        final String schoolDistrictCode = parcel.getSchoolDistrictCode();
        final Boolean containsHomesteadExemptionValues = parcel.containsHomesteadExemptionValues();
        final String taxBillMailingAddressLine1 = parcel.getTaxBillMailingAddressLine1();
        final String taxBillMailingAddressLine2 = parcel.getTaxBillMailingAddressLine2();
        final String taxBillMailingAddressLine3 = parcel.getTaxBillMailingAddressLine3();
        final String taxBillMailingAddressLine4 = parcel.getTaxBillMailingAddressLine4();
        final Date transferDate = parcel.getTransferDate();
        final Long transferYear = parcel.getTransferYear();
        final String ownerName1 = parcel.getOwnerName1();
        final String ownerName2 = parcel.getOwnerName2();
        final String ownerName3 = parcel.getOwnerName3();
        final String ownerAddress1 = parcel.getOwnerAddress1();
        final String ownerAddress2 = parcel.getOwnerAddress2();
        final String auditorsNeighborhoodCode = parcel.getAuditorsNeighborhoodCode();
        final String floodInfo = parcel.getFloodInfo();
        final String propertyClass = parcel.getPropertyClass();
        final Long numberOfPropertyCards = parcel.getNumberOfPropertyCards();
        final Double acreage = parcel.getAcreage();
        final Double lastSalePrice = parcel.getLastSalePrice();
        final Double totalTaxableValue = parcel.getTotalTaxableValue();
        final String city = parcel.getCity();
        final String state = parcel.getState();
        final String zipcode = parcel.getZipcode();
        final String descriptionLine1 = parcel.getDescriptionLine1();
        final String descriptionLine2 = parcel.getDescriptionLine2();
        final String descriptionLine3 = parcel.getDescriptionLine3();
        final String taxDesignation = parcel.getTaxDesignation();
        final Double primaryBuildingAreaSquareFeet = parcel.getPrimaryBuildingAreaSquareFeet();
        final String dwellingType = parcel.getDwellingType();
        final Long totalRoomCount = parcel.getTotalRoomCount();
        final Long fullBathCount = parcel.getFullBathCount();
        final Long halfBathCount = parcel.getHalfBathCount();
        final Long bedroomCount = parcel.getBedroomCount();
        final String centralAirStyle = parcel.getCentralAirStyle();
        final String buildingCondition = parcel.getBuildingCondition();
        final Boolean hasFireplaces = parcel.hasFireplaces();
        final String buildingGrade = parcel.getBuildingGrade();
        final String height = parcel.getHeight();
        final Double storyCount = parcel.getStoryCount();
        final String yearBuilt = parcel.getYearBuilt();
        final String propertyType = parcel.getPropertyType();
        final String wallCode = parcel.getWallCode();
        final Double latitude = parcel.getLatitude();
        final Double longitude = parcel.getLongitude();

        final String transferDateString = DateUtil.timestampToDatetimeString(transferDate.getTime());

        final Json json = new Json(false);

        json.put("id", id);
        json.put("parcelId", parcelId);
        json.put("exemptPropertyAppraisalLandValue", exemptPropertyAppraisalLandValue);
        json.put("exemptPropertyAppraisalBuildingValue", exemptPropertyAppraisalBuildingValue);
        json.put("exemptPropertyAppraisalTotalValue", exemptPropertyAppraisalTotalValue);
        json.put("taxablePropertyAppraisalLandValue", taxablePropertyAppraisalLandValue);
        json.put("taxablePropertyAppraisalBuildingValue", taxablePropertyAppraisalBuildingValue);
        json.put("taxablePropertyAppraisalTotalValue", taxablePropertyAppraisalTotalValue);
        json.put("auditorsMapNumber", auditorsMapNumber);
        json.put("auditorsRoutingSequence", auditorsRoutingSequence);
        json.put("appraisalLandUseCode", appraisalLandUseCode);
        json.put("currentAgriculturalUseValue", currentAgriculturalUseValue);
        json.put("schoolDistrictCode", schoolDistrictCode);
        json.put("containsHomesteadExemptionValues", containsHomesteadExemptionValues);
        json.put("taxBillMailingAddressLine1", taxBillMailingAddressLine1);
        json.put("taxBillMailingAddressLine2", taxBillMailingAddressLine2);
        json.put("taxBillMailingAddressLine3", taxBillMailingAddressLine3);
        json.put("taxBillMailingAddressLine4", taxBillMailingAddressLine4);
        json.put("transferDate", transferDateString);
        json.put("transferYear", transferYear);
        json.put("ownerName1", ownerName1);
        json.put("ownerName2", ownerName2);
        json.put("ownerName3", ownerName3);
        json.put("ownerAddress1", ownerAddress1);
        json.put("ownerAddress2", ownerAddress2);
        json.put("auditorsNeighborhoodCode", auditorsNeighborhoodCode);
        json.put("floodInfo", floodInfo);
        json.put("propertyClass", propertyClass);
        json.put("numberOfPropertyCards", numberOfPropertyCards);
        json.put("acreage", acreage);
        json.put("lastSalePrice", lastSalePrice);
        json.put("totalTaxableValue", totalTaxableValue);
        json.put("city", city);
        json.put("state", state);
        json.put("zipcode", zipcode);
        json.put("descriptionLine1", descriptionLine1);
        json.put("descriptionLine2", descriptionLine2);
        json.put("descriptionLine3", descriptionLine3);
        json.put("taxDesignation", taxDesignation);
        json.put("primaryBuildingAreaSquareFeet", primaryBuildingAreaSquareFeet);
        json.put("dwellingType", dwellingType);
        json.put("totalRoomCount", totalRoomCount);
        json.put("fullBathCount", fullBathCount);
        json.put("halfBathCount", halfBathCount);
        json.put("bedroomCount", bedroomCount);
        json.put("centralAirStyle", centralAirStyle);
        json.put("buildingCondition", buildingCondition);
        json.put("hasFireplaces", hasFireplaces);
        json.put("buildingGrade", buildingGrade);
        json.put("height", height);
        json.put("storyCount", storyCount);
        json.put("yearBuilt", yearBuilt);
        json.put("propertyType", propertyType);
        json.put("wallCode", wallCode);
        json.put("latitude", latitude);
        json.put("longitude", longitude);

        return json;
    }
}
